### ISSUE TITLE
Replace `path` with Object ID for roles and permissions authorisation

### ISSUE THREAD

**Issue by muloem** [akvo/akvo-flow#1215]
The implementation of roles and permissions uses the `path` of a `Survey` or `Folder` as the means to verify the authorisation of a user against that entity.  However, the paths are brittle as they break of an upper level `Folder` or `Survey` is renamed.  The consequence of this change is that users in some cases no longer have access to the `Survey` or `Folder` entities, and in other cases the user cannot even see these entities.  

**Proposed solution:** revise the implementation to use the object ids, which never change, as a means for checking authorisation.

**Comment by muloem** [comment]
### TODO list

- [ ] Revise domain model, `Surveys`, `SurveyGroup` and `SurveyInstances` entities
    - [ ] Create, Read, Update, Delete Entities

- [ ] Create, Update user authorization based on Object Id

- [ ] Filter all `GET` requests internally
    - [ ] /rest/survey_instances
    - [ ] /rest/survey_groups
    - [ ] /rest/surveys

- [ ] Revise RequestUriVoter functions for authorisation check

- [ ] Authorization for `/rest/survey_instances` 
    - [ ] `POST` / `PUT`
    - [ ] `DELETE`
    - [ ]  UI enable/hide delete link (inspect data and monitoring tabs)

- [ ] Authorization for `/rest/survey_groups` 
    - [ ] `POST` / `PUT`
    - [ ] `DELETE`
    - [ ]  UI Show/Hide Icons (Create, Edit, Delete)

- [ ] Authorization for `/rest/surveys` 
    - [ ] `POST` / `PUT`
    - [ ] `DELETE`
    - [ ]  UI Show/Hide Icons (Create, Edit, Delete)

**Comment by muloem** [comment]
@loicsans @Kiarii @mtwestra @janagombitova @iperdomo @jonase 

When we delete a `Survey` or `SurveyGroup` the associated permission will no longer be valid as its associated to the ID.  I'd like opinions on the preferable course of action in this case?  Delete the associated permission, or highlight it with a message that the associated entity has been deleted?

**Comment by iperdomo** [comment]
In traditional RDMBS you can describe the preferred action, `ON DELETE CASCADE`, `ON DELETE RESTRICT` See: http://www.postgresql.org/docs/current/static/ddl-constraints.html#DDL-CONSTRAINTS-FK

We have a history of making harder to delete entities, you need to first clean up all child objects and then you can delete the parent. If a user wants (and confirms) that he/she wants to delete an entity, we should help. So `ON DELETE CASCADE` is easier from a user perspective. I would suggest we should delete the associated permissions/roles.

**Comment by jonase** [comment]
I agree with Iván that we should delete the associated permission. It's difficult to imagine a use case where a "dangling" permission would be useful and the deleted entity id will never be reused (AFAIK).

**Comment by muloem** [comment]
### User Roles and Permissions Test Plan

**Pre-test preparation**

1. You will need at least two browsers to test or use multiple private browser sessions to isolate the user login information in each.

2. You need three separate Google accounts for testing.

3. You need to create/define a super user. Take an existing user account (`TestUser1`) and convert to a super admin via the data store.(set `superAdmin =True` and `permission list = 0`)

4. Ideally the test instance already has a couple of folders containing surveys, forms and data (responses) associated with the forms.



#### Test 1: Super Admin (`TestUser1`) Basic Login + Permissions

1. Login with super user account `TestUser1`

**Expected:**

* Under the `Projects` tab a list of all folders should be visible

* The `Users` tab should be visible

* Under the `Data` tab the user should be able to select all surveys and forms present on the system and view the associated data

* It should be possible to run a full suite of regression tests with this user without any restrictions


#### Test 2: Super Admin (`TestUser1`) User Administration

**Pre test prep (overlaps with regression / survey folder testing)**

* Create at least 2 different top level folders containing some sub folders with at least one of the sub folders containing at least one survey with one test form.

* Assign these forms to a device and submit a few data points for each form.

* Verify that the responses are visible.


**Test 2a - User creation**

1. Go to the `Users > Dashboard Users` tab

2. Add a new user (`TestUser2`) with the *second* email address from the test prep steps.

3. Tick the box to assign this user as an `Administrator`

**Expected:**

* The user should be visible in the list of users



**Test 2b - User update**

1. Select Edit next to the `TestUser2` just created and update this user's information (Name). 

**Expected:** 
* Verify that the user information is correctly  updated



**Test 2c - User roles definition**

1. Go to the `Users > Roles and Permissions` tab

2. Add a new role (`Administrator1`) with the first four permissions ticked

3. Save and verify that the role is created with the appropriate list of permissions

4. Edit the role and tick the rest of the permissions

5. Save and verify that the list is updated to reflect all permissions

6. Create a second role (`Administrator2`) with all permissions ticked

7. Save and verify that the the role is created with the list of permissions

8. Delete the role (`Administrator2`)

9. Verify that the role is correctly deleted from the list



**Test 2d - Assign User Roles**

1. Go to the `Users > Dashboard users` tab

2. Select Edit `TestUser2`

3. In the roles and permissions section select the role `Administrator1` and select one of the folders created in the pre-test prep for test 2. Click `Add`. 

4. Select the same role and pair it with the second folder created in the pre-test prep for test 2.

**Expected:**

* In the list of users the `TestUser2` should show the assigned role and the folders to which the assigned role corresponds




#### Test 3: Admin (`TestUser2`) Basic Login + Permissions

1. In a separate browser (or private browsing window), login with the credentials of `TestUser2`.

**Expected:**

* *Only* the two folders created in the pre-test preparation should be visible.

* The user should be able to browse these folders and perform all actions e.g. add sub folders, edit sub folders and forms

* The `Data` tab should be visible with only the list of surveys from the two folders shown and the data from the forms in these surveys visible.

* The `Users` tab should be visible

* Under the `Users` tab `TestUser1` should *not* be visible in the list of users

* It should be possible to run a full suite of regression tests for this user, however, these tests should only be restricted to forms and data of the two folders assigned and any contained sub folders, i.e. you should *not* be able to run these tests on forms or data (responses) outside these two folders.


#### Test 4: Admin (`TestUser2`) User Administration 

**Test 4a - User creation**

1. Go to the `Users > Dashboard Users` tab

2. Add a new user (`TestUser3`) with the *third* email address from the test prep steps.


**Expected:**

The user should be visible in the list of users


**Test 4b - User update**

1. Select Edit next to the `TestUser3` just created and update this user's information (Name). 

**Expected:**
* Verify that the user information is correctly  updated



**Test 4c - User roles definition**

1. Go to the `Users > Roles and Permissions` tab

2. Add a new role (`UserRoleReadAndWrite1`) with the *four* permissions connected to *Forms* selected.

3. Save and verify that the role is created with the appropriate list of permissions

4. Create a second role (`UserRoleReadOnly2`) with only the `Access Forms` permission selected

5. Save and verify that the role is created correctly



**Test 4d - Assign User Roles - Read and Write**

1. Go to the `Users > Dashboard users` tab

2. Select Edit `TestUser3`

3. In the roles and permissions section select the role `UserRoleReadAndWrite1` and select one of the *Surveys* created in the pre-test prep for test 2. Click `Add`. 

4. Select the second role `UserRoleReadOnly2` and pair it with a survey in the second folder created in the pre-test prep for test 2. Click `Add`.

**Expected:**

* In the list of users the `TestUser2` should show the assigned role and the folders to which the assigned role corresponds


#### Test 5: User (`TestUser3`) Basic Login + Permissions

1. In a separate browser (or private browsing window), login with the credentials of `TestUser3`.

**Expected:**

* *Only* the two folders created in the pre-test preparation should be visible.

* The user should be able to browse these folders and see all the surveys and forms.

* The user should be able to perform all actions e.g. add sub folders, edit sub folders and forms in *only* the first folder.

* The user should *not* be able to create and edit sub folders in the second folder

* The `Data` tab should be visible with only the list of surveys from the two folders shown and the data from the forms in these surveys visible.

* The `Users` tab should *not* be visible

* It should be possible to run the full suite of regression tests with this user save for the restriction to folders and permissions and the `Users` tab actions.

**Comment by muloem** [comment]
@rumca the test plan for this is taken from #818 and I will make some adaptations for the newly created permissions e.g data cleaning.

**Comment by muloem** [comment]
@rumca I made some adaptations to the test plan for roles and permissions

**Comment by rumca** [comment]
On first glance, the above fix seems to resolved the issue whereby subfolders were not appearing when a role was applied to that particular sub (and not its parent folder also).

I'll re-run the test plans above just to make sure everything still works as expected.

**Comment by rumca** [comment]
The above test plans are all passing - I've tried to break it through other tests as well and haven't been able to so far :+1: 

@muloem @jonase one thing to note, which I think we should address in a more graceful manner at some point, when a user with read only permissions tries to delete forms/questions they still have the UI available to them to do so. The request subsequently fails, but with no visual clue to the user. Perhaps we should just remove the delete options from the Survey editor all together when a user only has read only access?
