### ISSUE TITLE
Cartodb milestone 2

### ISSUE THREAD

**Issue by jonase** [akvo/akvo-flow#1389]
New features

* [x] Geoshapes [#1356]
* [x] Filter surveys/forms by user access rights
* [x] Hierarchical survey selection (?)

**Comment by janagombitova** [comment]
Fix issues based on feedback from users testing out the maps: 

* [ ] Fix date format 
* [ ] List of surveys is not identical in Maps tab and in Inspect data tab
* [ ] Add layer selection - use three layers we currently provide: terrain, streets, satellite
* [ ] Fix scrolling
   - **Proposal:** Disable scrolling on the Maps page entirely. Thus the header and footer will always be visible and the filter options will not disappear due to scrolling. When the user scrolls with the mouse over the map, map zooms in and out (as it currently does).
   - **Limitation:** This solution does make the map smaller, especially when previewing in smaller screens. However the confusion regarding the scrolling seems as a more pressing issue.

**Comment by akvotender** [comment]
Assigned to [Tender discussion #5910](http://flowhelp.akvo.org/discussions/problems/5910-ewb-usa-questions-on-a-couple-of-flow-glitches).

**Comment by janagombitova** [comment]
@kymni and @jonase Can you add a test plan and can you please review the date fixes if they are consistent throughout the dashboard? (as I assumed we use the iso standard and @muloem explained that is not the case)

**Comment by kymni** [comment]
@janagombitova @jonase code should be ready for reviewing now before testing can begin

**Comment by akvotender** [comment]
Assigned to [Tender discussion #5975](http://flowhelp.akvo.org/discussions/problems/5975-ssh4a-wash-survey-in-nepal).

**Comment by rumca** [comment]
removing this from the milestone as the code for it is committed against 1356

**Comment by janagombitova** [comment]
Issue completed - closing
