### ISSUE TITLE
Combination of all issues dealing with Roles and Permissions

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#1583]
* [ ] https://github.com/akvo/akvo-flow/issues/1558 Fix data view 
* [ ] https://github.com/akvo/akvo-flow/issues/1582 All folder role stronger than single folder role
* [ ] https://github.com/akvo/akvo-flow/issues/1529 All folders on the top of dropdown
* [ ] https://github.com/akvo/akvo-flow/issues/1528 Hide data cleaning tab
* [ ] https://github.com/akvo/akvo-flow/issues/991 Issue with count in R&P tab
* [ ] https://github.com/akvo/akvo-flow/issues/1364 Cannot remove a role due to broken count
* [ ] https://github.com/akvo/akvo-flow/issues/1157 Disallow more than one user account with same email
* [ ] https://github.com/akvo/akvo-flow/issues/1251 - should be solved, needs checking

**Comment by janagombitova** [comment]
Using labelling as an alternative to keep overview of priorities, projects and work progress. Closing this issue for now
