### ISSUE TITLE
Monitoring: No more need to send all data points to a device

### ISSUE THREAD

**Issue by janagombitova** [akvo/akvo-flow#2796]
# Context 

One of our goals is to ensure users can continuously monitor their data points on large scale. 

## Current monitoring in Flow

In Flow you can define a registration form and its connected monitoring forms in one survey. 

The registration form defines the object of your data collection. If you are interested in learning about the status of a water point in communities in your country, your registration form will hold the basic information about a water point - the information that defines it, that does not change (location, ID, photo, type). If you are interested in learning about the quality of education in schools in your programme, your data point will be a school and in the registration form you will ask questions as location, photo, when was it built, by who, etc. It you are interested in learning about farmers in your programme, then your data point will be a farmer and you will ask him questions in the registration form as her name, date of birth, photo, etc. 

The monitoring forms (one or many) will hold questions that you want to ask your subject of your data collection repetitively over the course of time to see change. In our case of water points one monitoring form can hold questions about the water quality, another monitoring form about the overall status of the water point as if it is functioning, clean, how many people are there, etc, all depending on what you want to analyse. In the school case your monitoring form can be an internal inspection form, another form can be about the satisfaction of the pupils, etc. In the farmer case a monitoring form can hold questions about his crops and yield, where another form on his nutrition. 

When in the field you first submit the registration form, this creates your data point. Now you can submit the monitoring form to that data point. Your first monitoring form submission will create your baseline and the following submissions will help you see change over time. The next time you come back to your data point, you will select the data point from the list of points on your device and submit another monitoring form submission. 

## Current issue
If you are monitoring all water points in a region or country wide we are imagining thousands of data points to monitor. Currently in Flow once a registration form is submitted and a data point created any enumerator who is assigned the survey, can download the created data points to his device. This makes it possible that if Al registered point A, Isha can download also his point A and monitor it, not having the data points only available to Al. 

But if there are thousand points registered, this means once Al and Isha hit download on their Flow app **all thousand points will start downloading to their devices**. 
- takes a lot of time, bandwidth and storage on the device to download all data points (tested to download 6k data points on Amsterdam internet, took me over 3 hours with multiple retries) 
- in areas with low connectivity is it impossible 
- Al does not need to have all the data points as he is responsible to monitor only a certain group of them
- having so many data points, finding the one to monitor becomes painful for Al and Isha and possibly resulting in them selecting the wrong data point causing the submission to link to the wrong previous data creating an analysis headache and risk 
- having so many data points, it happens that Al sometimes by mistake makes two monitoring form submissions to the one data point in the round due to all the data points on his phone as it is hard to see which he already monitored

# Opportunity 

## How might we enable Al to only get the data points he needs to monitor and for Isha the points she need to monitor.

We see that there are multiple issues when monitoring data in the field: 
- Al does not select the right data point submitting information to the wrong one 
- Al submits a monitoring form twice in that round even though he should make one submission per point but finds it hard to see which he already worked on 
- Downloading data points to the device on low connectivity is impossible 

And we guess that by limiting the number of data points Al receives on his device will if not address then at least decrease the other problems.  

## What we are not doing 
When we researched monitoring we also learned about cases when monitoring was done with **random sampling** in this case monitoring is not done by going back to the same location, person or school to see the change for the specific data point but is done on a group as a whole. A random sample is defined, there people are interviewed and in the next round another random sample is defined and data is collected. In this case the data is compared for the aggregated group over the course of time. Flow forms can be used here, without the monitoring feature. 

We will not be investigating opportunities around supporting random sampling at this moment of time. 

# Documentation
Notes from user research: 
https://docs.google.com/spreadsheets/d/1qK13keQZ1rchlhLCBX3SNSudf5IXjnSdlQKRp5GrG8k/edit#gid=0

User journey and story map:
https://app.mural.co/t/akvo8194/m/akvo8194/1519979617595/9e87113d9211e9ead6ab12b98ea8ad51e8b8f079

**Comment by janagombitova** [comment]
# Mock up review 

Today we reviewed the current mock ups made by @Kiarii and suggested to: 
- look at better supporting Salim in making the decisions, so what does he need to do first and what next in the UI
- clarify more that the filters relate to data points 
- explore the fact that after selecting the survey Salim might first want to see the available data points before he selects or filters them out to add to the assignment as a whole or per device
- add the concept of question groups

We also agreed that Salim will only assign data points and see any functionality related to this, when he selects a monitoring survey and monitoring forms to assign. If he selects a non-monitoring survey, he has no data points to assign thus does not see the functionality. If he selects a monitoring survey but only the registration form, he is not going to monitor yet thus also has no data points to assign, so does not see the functionality. 

The filters will only be based on the registration form. We agreed to limit what the filters can be based on further, like only option and cascade question answers and some meta data columns as submission date. We still need to define the filters in more detail. 

# What is an assignment 
When discussing the question of what role do dates play in an assignment and what do we sync in in term of previously made submissions - what is assigned or everything, we realised we need to first answer to big question: **What is an assignment?** We found 2 answers: 
1. A way of getting survey forms to devices
2. A task to collect data. 

## Assignment = task

An assignment as a task means that an assignment is something Salim gives to Al to do. So Al is given an assignment that he needs to complete. This assignment holds survey forms, data points and has a timeframe of completion. It has its rules. It holds What forms Al has to collect data for, Which data points (if that applies) he needs to update, When must he do this work. In this case then Al should not see surveys on his device, but assignments. Then the assignment date can have a stronger role also enforcing open/closed submission dates. 

## Decision
We agreed to delay the decision as: 
- we do not want to implement two big changes at once and the monitoring change has more priority right now 
- we want to learn more from users on how they understand assignments and how they manage the data collection process
- if we want to enforce the task concept then we should move to app users first. Currently one device can have more than one user thus enforcing tasks per user in the current concept will complicate the workflow on the app 

# Other questions

Currently, you can add more different survey forms to one assignment (survey A is monitoring and I assign form 1, survey B is not monitoring and I assign its form too, survey C is monitoring and I assign form 1 and 2). How will we support this? 

Eventually, how will we break down the implementation to small chunks we can get out to users quickly?

**Comment by janagombitova** [comment]
Mock ups: https://projects.invisionapp.com/share/TZP8HSGRB5N#/screens

Next we will review them with the team, define the 1st slice, roll up our sleeves and build.

**Comment by janagombitova** [comment]
Today we discussed with the team how to make the implementation happen and agreed to go about it in 2 steps: 

# 1st step 
- one assignment per survey rule (but one survey can be used in multiple assignments) 
- redesign current Assignments UI (how an assignment is set up and how the list of existing assignments will look like) 
- no changes to how dates work 
- re-write frontend to React 
- add tests 

# 2nd step will be  
- add the option to assign data points by searching by point name and ID 
- search will not support autosuggest or auto complete
- Salim types in a word or number and hits search -> sees a list of data points that in their data point name or ID have what he searched for -> Salim decides which of these data points he assigns (one by one or by 'assigning all')
- might change the backend to move away from our current datastore on Google to a postgres one depending on how we move forward with Flow-Lumen work 

# Future changes 
- eventually once the two steps are completed we will gather input on how things are working and what other changes need to be made 
- we will also look at adding assigning data points by form data (option or cascade answers) 
- we will also research later what the role of an assignment is as a task not only for Salim but also Al collecting the data

**Comment by janagombitova** [comment]
Updates mockups from @Kiarii are here: https://projects.invisionapp.com/share/NHQGVLB2EKX#/346093699_0-0_Assignments_ES

**Comment by janagombitova** [comment]
When we discussed this change (Step 2) we based it on the assumption that data points are registered. These are then assigned to a device. In a talk we had, Joy asked a valid question: "What about the situation when the data point does not exist yet but I want to make sure that if it has this word in the name (answer to a cascade for example) (or this question is answered in a certain way) that it is sent to this enumerator?"

So is it possible that the assignment rather than working on the principle "this data point goes to this device", it works on the principle that "any data point matching these criteria goes to this device"?

@muloem @Kiarii @kymni What do you think? Should we talk more?

**Comment by muloem** [comment]
> In a talk we had, Joy asked a valid question: "What about the situation when the data point does not exist yet but I want to make sure that if it has this word in the name (answer to a cascade for example) (or this question is answered in a certain way) that it is sent to this enumerator?"

I believe we had the discussion around this kind of data point filtering.  This scenario sounds similar to what @Kiarii and @loicsans mentioned, for example, _have datapoints going to a device/user based on the response to a cascade question that referred to a specific district_.  Correct me if I am wrong but I believe we decided that as a first step we would have the basic assignment working in place and then build upon that to enable this more advanced/automated datapoints assignment

**Comment by Kiarii** [comment]
Yes, I have the feeling that we had settled to increment the feature after rolling out a working version, on which also we could garner some feedback and see what direction might be of more value..

**Comment by janagombitova** [comment]
Perfect! I just wanted to make sure that the next step will also handle data points that do not exist yet and I was not sure if we had the same understanding of it. But we do. 

I absolutely agree to stick to the step by step approach. So we are well on track.

**Comment by janagombitova** [comment]
With 1.9.47 release we pushed out the change where the assignments list is rewritten to React. The next steps to follow are: 
* [ ] ensure existing assignments are only based on one survey 
* [ ] rewrite current assignment editor to react + redesign it according to the mockups 
* [ ] add data point assignment functionality based on searching by name and ID 
* [ ] add option to assign data points based on criteria from the registration form 

@kymni and @muloem and @stellanl can you create separate issues for these tasks and maybe break them down even more? Then we can keep this issue as the overall epic and work with the smaller issues in the sprint. Cheers.

**Comment by janagombitova** [comment]
The final mockups are here: https://projects.invisionapp.com/share/5YUUUPXF7DA#/screens

**Comment by muloem** [comment]
After reviewing the mockups with @iperdomo @stellanl and @Kiarii, we concluded that implementing the _Assign all datapoints_ functionality has a number of problems associated with it

* First it creates the issue where if we have a survey with a large number of datapoints, we will run into the same performance issues that we want to solve by selective datapoint assignment.  i.e. if there are too many datapoints, the backend will cancel the request halfway through and the device user doesnt get all the datapoints they expect.

* The usability of very large number of datapoints on the devices is questionable.

* We can potentially end up with an exponential explosion of entities on the backend related to datapoint assignments, which will also be a problem for the performance of this feature.

Based on these issues, we concluded that we will put on hold the part of assigning all datapoints to a single device.  For now we will only implement that part where the user is able to search for datapoints by _display name_ or by _datapoint ID_.

**Comment by Kiarii** [comment]
Notes and comments on current state of implementation:
- perhaps we should unify the folder structure dropdown navigation with the rest of flow
<img width="275" alt="Screenshot 2020-02-19 at 10 35 08" src="https://user-images.githubusercontent.com/12692444/74816352-a830d000-5303-11ea-903d-ceda7e0905cf.png">

- Assignment names in the Assignments page should be left aligned for ease of scanning and reading, also to keep consistency with the rest of asset lists in Flow. A side note; not sure why we refer to Assignments and Devices as Assignment List and Device List.. it is an unnecessary redundancy and only increases the number elements on the interface that the user has to pay attention to 

- Enable only the selection of Device groups when adding devices to assignment; this should simplify the task. Lets reserve device group management to Devices page. I had also commented about this in Slack
<img width="364" alt="Screenshot 2020-02-19 at 10 40 23" src="https://user-images.githubusercontent.com/12692444/74816913-bd5a2e80-5304-11ea-83d6-9cf9df65908e.png">

- lets keep the survey structure browsing drop downs on a single line as with other pages as well instead of breaking it when these exceed two;
<img width="335" alt="Screenshot 2020-02-19 at 10 52 49" src="https://user-images.githubusercontent.com/12692444/74817770-28583500-5306-11ea-989f-7fcac126df17.png">

-

**Comment by Kiarii** [comment]
Since assigning datapoints to a device is not obvious, the idea had been that by adding devices, the first device in the list would automatically be selected for the purpose, to make it clear to the user what more they can do..e.g.
![image](https://user-images.githubusercontent.com/12692444/74834510-3a48d080-5324-11ea-9d6a-f7c94acc72a7.png)

**Comment by Kiarii** [comment]
@marvinkome there is a bug with the published form; tricky to describe but I captured it:
![published forms bug](https://user-images.githubusercontent.com/12692444/76842641-3df84600-6843-11ea-9f51-4cca14d5be60.gif)

**Comment by Kiarii** [comment]
<img width="213" alt="Screenshot 2020-03-17 at 11 49 37" src="https://user-images.githubusercontent.com/12692444/76844155-90d2fd00-6845-11ea-8d52-b50a034c5ddc.png">

lets shorten the first option to the following, there is no need to be repetitive when these two are just next to each other

![image](https://user-images.githubusercontent.com/12692444/76844196-9f211900-6845-11ea-8167-e1b6f9ea50f6.png)

**Comment by Kiarii** [comment]
* long device list breaks the screen layout; the side bar should scroll independently so that the essential actions such as Save, Navigating back, the Device and Form elements are in view.. 
<img width="671" alt="Screenshot 2020-03-18 at 10 54 00" src="https://user-images.githubusercontent.com/12692444/76942771-f3d89880-6906-11ea-9ce8-b4c3b9d3f398.png">

**Comment by Kiarii** [comment]
* similar issue with several forms; the screen layout breaks
<img width="860" alt="Screenshot 2020-03-18 at 11 18 33" src="https://user-images.githubusercontent.com/12692444/76944786-4798b100-690a-11ea-8b2c-f3730d22ad03.png">

**Comment by marvinkome** [comment]
This has been reported here #3475

**Comment by muloem** [comment]
Datapoint assignemts

![new-datapoints-assignment](https://user-images.githubusercontent.com/533336/78558450-dc5c4380-7812-11ea-9334-c5695ade8024.gif)

**Comment by janagombitova** [comment]
This epic intended to get assigning data points to devices out in the open. The initial implementation is out there. The implementation is that by default all devices in an assignment get all data points assigned and Salim needs to explicitly assign specific data points if he wants to. 

The next step (now in progress) is to improve this current implementation. We have created separate issues to manage the work, they are labelled '1 - Assignments' and added to the 'To do' column. 

We will keep this iteration live for a certain period of time to learn about it and then pivot. The pivot-steps will be captured in separate issues linking to this one. 

So it is time we close this monster. Well done team!
